package:
  name: grass
  version: 7.8.3

source:
  url: https://grass.osgeo.org/grass78/source/grass-7.8.3.tar.gz
  patches:
    - platform.make.in.patch [osx]
    - platform.make.in-linux.patch [linux]
    - loader.py.patch
    - rules.make.patch [osx]
    - rules.make.patch [linux]
    - aclocal.m4.patch
    - configure.patch
    - install.make.patch
    - module.make.patch [osx]
    - shlib.make.patch [osx]

requirements:
  build:
    - clang_osx-64 [osx]
    - clangxx_osx-64 [osx]
    - gcc_linux-64 [linux]
    - gxx_linux-64 [linux]
    - python=3.7.8
    - setuptools
    - numpy
    - gdal >2
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - pillow
    - wxpython
    - sqlite
    - jpeg
    - libpng
    - libtiff
    - pkg-config [osx]
    - libiconv
    - fftw
    - blas
    - giflib
    - proj=6.2.1
    - geos
    - krb5
    - gettext
    - ghostscript
    - zstd
    - pdal
    - ply
    - poppler

  run:
    - libgcc
    - python=3.7.8
    - setuptools
    - numpy
    - gdal >2
    - freetype
    - cairo
    - matplotlib
    - pandoc
    - pil
    - wxpython
    - sqlite
    - jpeg
    - libpng
    - libtiff
    - pkg-config [osx]
    - libiconv
    - fftw
    - blas
    - giflib
    - proj=6.2.1
    - geos
    - krb5
    - gettext
    - ghostscript
    - zstd
    - pdal
    - ply
    - poppler

build:
  number: 0

about:
  summary: Geographic Resources Analysis Support System
  description: |
    GRASS GIS, commonly referred to as GRASS (Geographic Resources
    Analysis Support System), is a free and open source Geographic
    Information System (GIS) software suite used for geospatial data
    management and analysis, image processing, graphics and maps
    production, spatial modeling, and visualization.
  home: https://grass.osgeo.org/
  license: GPLv2
  dev_url: https://grass.osgeo.org/development/

